[tool.poetry]
name = "tomlantic"
version = "0.1.0"
description = "marrying pydantic models and tomlkit documents"
authors = ["Mark Joshwel <mark@joshwel.co>"]
license = "Unlicense"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = ">=2.0"
tomlkit = ">=0.8"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
isort = "^5.13.2"
mypy = "^1.8.0"

[tool.black]
line-length = 90

[tool.isort]
line_length = 90
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
